---
- hosts: local
  connection: local
  tasks:
    - name: load variables
      include_vars: "{{ packer_config_file }}"
    - name: load secrets
      include_vars: secrets.yml
    - name: get cloud image
      get_url:
        url: "{{ downloadurl }}"
        dest: ./image.{{ cloud_image_format }}
    - name: convert image
      shell: "sudo docker run --rm=true -v $PWD:/tmp schvin/qemu-img convert -p -O vpc image.{{ cloud_image_format }} image.vhd"
    - name: rsync image to srep001
      shell: "rsync ./image.vhd root@srep001.hay01.gdaas.com:/root/data/cloud/{{ name }}.vhd"
    - name: Register template on cloudstack
      local_action:
        module: cs_template
        api_url: "{{ cs_api_url }}"
        api_key: "{{ cs_api_key }}"
        api_secret: "{{ cs_api_secret_key }}"
        name: "{{ name }}"
        url: "http://srep001.hay01.gdaas.com/cloud/{{ name }}.vhd"
        hypervisor: XenServer
        format: VHD
        cross_zones: yes
        os_type: "{{ osdescription }}"
        poll_async: true
    - name: Check template extracted
      local_action:
        module: cs_template
        api_url: "{{ cs_api_url }}"
        api_key: "{{ cs_api_key }}"
        api_secret: "{{ cs_api_secret_key }}"
        name: "{{ name }}"
        state: extracted
    - name: Create packer_config.json
      template: src=./ansible_templates/packer_config.json.j2 dest=./packer_config.json
    - name: Build and provision offical template
      shell: "packer build -var-file=packer_config.json template.json"