name: debian863
displaytext: 20GB
osdescription: Debian 8.6.3
osversion: 7
oscategory: debian
format: vhd
hypervisor: XenServer
extractable: true
featured: false
public: false
passwordenabled: false
zoneid: -1
url: http://srep001.hay01.gdaas.com
downloadurl: http://cdimage.debian.org/cdimage/openstack/current/debian-8.6.3-20161129-openstack-amd64.qcow2
ssh_username: debian
cloud_image_format: qcow2
template_output_name: debian863-gold