name: fedora25
displaytext: 20GB
osdescription: Other (64-bit)
osversion: 7
oscategory: fedora
format: vhd
hypervisor: XenServer
extractable: true
featured: false
public: false
passwordenabled: false
zoneid: -1
url: http://srep001.hay01.gdaas.com
downloadurl: https://download.fedoraproject.org/pub/alt/atomic/stable/Fedora-Atomic-25-20161207.0/CloudImages/x86_64/images/Fedora-Atomic-25-20161207.0.x86_64.qcow2
ssh_username: fedora
cloud_image_format: qcow2
template_output_name: fedora25-gold