---
name: centos72
displaytext: 20GB
osdescription: CentOS 7
osversion: 7
oscategory: centos
format: vhd
hypervisor: XenServer
extractable: true
featured: false
public: false
passwordenabled: false
zoneid: -1
url: http://srep001.hay01.gdaas.com
downloadurl: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
ssh_username: centos
cloud_image_format: qcow2