---
- hosts: local
  connection: local
  tasks:
    - name: load variables
      include_vars: config.yml
    - name: get cloud image
      get_url:
        url: "{{ downloadurl }}"
        dest: ./image.qcow2
    - name: convert image
      shell: "sudo docker run --rm=true -v $PWD:/tmp schvin/qemu-img convert -p -O vpc image.qcow2 image.vhd"
    - name: rsync image to srep001
      shell: rsync ./image.vhd root@srep001.hay01.gdaas.com/root/data/cloud/centos72.vhd