---
- hosts: local
  connection: local
  tasks:
    - name: load variables
      include_vars: config.yml 
    - name: get cloud image
      get_url:
        url: "{{ downloadurl }}"
        dest: /tmp/image.qcow2
