---
- hosts: local
  connection: local
  tasks:
    - name: create dummy file
      get_url:
        url: http://www.google.be
        dest: ./google.html
    - name: load variables
      include_vars: config.yml
    - shell: echo "image_$(date +%d-%m-%y-%H-%M-%S)"
      register: image_name
    - debug:
        msg: "{{ image_name.stdout_lines[0] }}"
    - name: get cloud image
      get_url:
        url: "{{ downloadurl }}"
        dest: ./image.qcow2
    - name: convert image
      shell: "sudo docker run --rm=true -v $PWD:/tmp schvin/qemu-img convert -p -O vpc image.qcow2 image.vhd"
    - copy:
        src: ./image.vhd
        dest: /data/cloud/centos72.vhd
        delegate_to: srep001.hay01.gdaas.com

